excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://leovbranco.github.io
name: Awesome
description: My awesome new site
author: Leonardo Branco
avatar: http://www.gravatar.com/avatar/b38a46b78011e2b6f0813b20e300030b?s=120&d=mm&r=g
ga_domain: 
ga_tracking_id: 
theme: jekyll-theme-minimal